"""Canonical public Agent SDK surface."""

from agiwo.agent.agent import Agent, AgentExecutionHandle
from agiwo.agent.intent import (
    InMemorySessionIntentStore,
    IntentEntry,
    IntentEntryKind,
    SessionIntent,
    SessionIntentStore,
    SQLiteSessionIntentStore,
    create_session_intent_store,
    summarize_run_report,
)
from agiwo.agent.main_agent import MainAgent, MainAgentState
from agiwo.agent.queue import QueueItem, QueueItemKind
from agiwo.agent.spec import AgentSpec
from agiwo.agent.models.config import (
    AgentConfig,
    AgentOptions,
    AgentStorageOptions,
    RunLogStorageConfig,
    TraceStorageConfig,
)
from agiwo.agent.hooks import (
    HookCapability,
    HookGroup,
    HookPhase,
    HookRegistration,
    HookRegistry,
    decision_support,
    observe,
    transform,
)
from agiwo.agent.models.input import (
    ChannelContext,
    ContentPart,
    ContentType,
    MessageContent,
    UserInput,
    UserMessage,
)
from agiwo.agent.models.log import (
    AssistantStepCommitted,
    build_committed_step_entry,
    CommittedStep,
    CompactionApplied,
    CompactionFailed,
    ContextAssembled,
    HookFailed,
    LLMCallCompleted,
    LLMCallStarted,
    MessagesRebuilt,
    RunFailed as RunFailedEntry,
    RunFinished,
    RunLogEntry,
    RunLogEntryKind,
    RunRolledBack,
    RunStarted,
    TerminationDecided,
    ToolStepCommitted,
    UserStepCommitted,
)
from agiwo.agent.models.execution import RunTreeRole, RunExecutionRequest
from agiwo.agent.models.finalization import RunFinalizationResult
from agiwo.agent.models.run import MemoryRecord
from agiwo.agent.models.run import (
    RunMetrics,
    RunOutput,
    RunStatus,
    RunView,
    TerminationReason,
)
from agiwo.agent.models.runtime_decision import (
    CompactionDecisionView,
    CompactionFailureDecisionView,
    RollbackDecisionView,
    RuntimeDecisionState,
    TerminationDecisionView,
)
from agiwo.agent.models.step import (
    LLMCallContext,
    MessageRole,
    StepDelta,
    StepMetrics,
    StepView,
)
from agiwo.agent.models.stream import (
    AgentStreamItem,
    AgentStreamItemBase,
    CompactionAppliedEvent,
    CompactionFailedEvent,
    MessagesRebuiltEvent,
    RunCompletedEvent,
    RunFailedEvent,
    RunRolledBackEvent,
    RunStartedEvent,
    StepCompletedEvent,
    StepDeltaEvent,
    TerminationDecidedEvent,
    stream_items_from_entries,
)
from agiwo.agent.storage.base import RunLogStorage

__all__ = [
    "Agent",
    "AgentExecutionHandle",
    "AgentSpec",
    "AgentConfig",
    "AgentOptions",
    "AgentStorageOptions",
    "AgentStreamItem",
    "AgentStreamItemBase",
    "RunTreeRole",
    "AssistantStepCommitted",
    "build_committed_step_entry",
    "ChannelContext",
    "CommittedStep",
    "CompactionAppliedEvent",
    "CompactionApplied",
    "CompactionFailed",
    "CompactionFailedEvent",
    "CompactionDecisionView",
    "CompactionFailureDecisionView",
    "ContentPart",
    "ContentType",
    "ContextAssembled",
    "HookFailed",
    "LLMCallContext",
    "LLMCallCompleted",
    "LLMCallStarted",
    "MainAgent",
    "MainAgentState",
    "MemoryRecord",
    "SessionIntent",
    "SessionIntentStore",
    "SQLiteSessionIntentStore",
    "create_session_intent_store",
    "summarize_run_report",
    "QueueItem",
    "QueueItemKind",
    "MessagesRebuiltEvent",
    "MessagesRebuilt",
    "MessageContent",
    "MessageRole",
    "HookCapability",
    "HookGroup",
    "HookPhase",
    "HookRegistration",
    "HookRegistry",
    "InMemorySessionIntentStore",
    "IntentEntry",
    "IntentEntryKind",
    "RunFailedEntry",
    "RunFinished",
    "RunCompletedEvent",
    "RunFailedEvent",
    "RunLogEntry",
    "RunLogEntryKind",
    "RunRolledBack",
    "RunRolledBackEvent",
    "RunExecutionRequest",
    "RunFinalizationResult",
    "RunMetrics",
    "RunOutput",
    "RunStarted",
    "RunStartedEvent",
    "RunStatus",
    "RunLogStorageConfig",
    "RunLogStorage",
    "RunView",
    "RollbackDecisionView",
    "RuntimeDecisionState",
    "StepCompletedEvent",
    "StepDelta",
    "StepDeltaEvent",
    "StepMetrics",
    "StepView",
    "TerminationDecided",
    "TerminationDecidedEvent",
    "TerminationDecisionView",
    "TerminationReason",
    "TraceStorageConfig",
    "ToolStepCommitted",
    "UserStepCommitted",
    "UserInput",
    "UserMessage",
    "decision_support",
    "observe",
    "stream_items_from_entries",
    "transform",
]
