"""Tool Result Retrospect — context optimisation for verbose tool outputs.

This module encapsulates the core logic for the *retrospect* mechanism:

* **Trigger check** — decides whether a system-notice should be injected
  after a tool result based on token/round thresholds.
* **Notice injection** — appends a ``<system-notice>`` tag to tool result
  content.
* **Retrospect execution** — offloads original verbose content to disk,
  replaces in-memory messages with concise placeholders, writes the
  ``condensed_content`` field on persisted steps, and cleans up the
  retrospect tool call itself from the live message list.
"""

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from agiwo.agent.models.config import AgentOptions
from agiwo.agent.models.run import RunLedger
from agiwo.agent.storage.base import RunStepStorage

if TYPE_CHECKING:
    from agiwo.agent.runtime.context import RunContext

logger = logging.getLogger(__name__)

_SYSTEM_NOTICE = (
    "\n\n<system-notice>"
    "Tool result is large. Please retrospect: if this result has limited "
    "value for your current goal, call retrospect_tool_result to replace "
    "it with a concise feedback summary."
    "</system-notice>"
)


def check_retrospect_trigger(
    config: AgentOptions,
    ledger: RunLedger,
    content: str,
    tool_name: str,
) -> bool:
    """Return *True* when a retrospect system-notice should be injected."""
    if not config.enable_tool_retrospect:
        return False
    if tool_name == "retrospect_tool_result":
        return False

    token_estimate = len(content) // 4

    return (
        token_estimate >= config.retrospect_token_threshold
        or ledger.retrospect_pending_rounds >= config.retrospect_round_interval
        or ledger.retrospect_pending_tokens
        >= config.retrospect_accumulated_token_threshold
    )


def update_retrospect_tracking(
    ledger: RunLedger,
    content: str,
) -> None:
    """Accumulate retrospect tracking counters after a tool result."""
    token_estimate = len(content) // 4
    ledger.retrospect_pending_tokens += token_estimate
    ledger.retrospect_pending_rounds += 1


def inject_system_notice(content: str) -> str:
    """Append the retrospect system-notice to *content*."""
    return content + _SYSTEM_NOTICE


def offload_to_disk(content: str, path: Path) -> str:
    """Write *content* to *path* and return a placeholder string."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return f"[ToolResult offloaded to {path}]"


async def execute_retrospect(
    *,
    feedback: str,
    messages: list[dict[str, Any]],
    ledger: RunLedger,
    storage: RunStepStorage,
    session_id: str,
    offload_dir: Path,
    step_lookup: dict[str, Any],
) -> str:
    """Execute a retrospect pass over recent tool messages.

    Parameters
    ----------
    feedback:
        The concise retrospect feedback generated by the agent.
    messages:
        The live ``RunLedger.messages`` list (mutated in-place).
    ledger:
        The current ``RunLedger`` (counters are reset).
    storage:
        ``RunStepStorage`` used for persisting ``condensed_content``.
    session_id:
        Current session id.
    offload_dir:
        Directory to write offloaded content files.
    step_lookup:
        Mapping of ``tool_call_id`` → ``StepRecord`` for steps in the
        retrospect range.

    Returns
    -------
    A summary string suitable for the tool result.
    """

    last_retrospect_seq = ledger.last_retrospect_seq
    retrospected_count = 0
    last_tool_call_id: str | None = None

    for msg in messages:
        if msg.get("role") != "tool":
            continue
        seq = msg.get("_sequence", 0)
        if seq <= last_retrospect_seq:
            continue

        tool_call_id = msg.get("tool_call_id", "")
        original_content = msg.get("content", "")
        if not original_content:
            continue

        offload_path = offload_dir / f"{tool_call_id}.txt"
        placeholder = offload_to_disk(original_content, offload_path)
        msg["content"] = placeholder
        retrospected_count += 1
        last_tool_call_id = tool_call_id

        step_info = step_lookup.get(tool_call_id)
        if step_info is not None:
            step_id = step_info.get("id", "")
            if step_id:
                await storage.update_step_condensed_content(
                    session_id, step_id, placeholder
                )

    if last_tool_call_id is not None and feedback:
        await _persist_feedback(
            messages,
            last_retrospect_seq,
            feedback,
            last_tool_call_id,
            step_lookup,
            storage,
            session_id,
        )

    _remove_retrospect_tool_call(messages)

    max_seq = 0
    for msg in messages:
        s = msg.get("_sequence", 0)
        if s > max_seq:
            max_seq = s
    ledger.last_retrospect_seq = max_seq
    ledger.retrospect_pending_tokens = 0
    ledger.retrospect_pending_rounds = 0

    logger.info(
        "retrospect_executed",
        session_id=session_id,
        retrospected_count=retrospected_count,
    )
    return f"Retrospect applied to {retrospected_count} tool result(s)."


async def _persist_feedback(
    messages: list[dict[str, Any]],
    last_retrospect_seq: int,
    feedback: str,
    target_tool_call_id: str,
    step_lookup: dict[str, Any],
    storage: RunStepStorage,
    session_id: str,
) -> None:
    """Append retrospect feedback to the last tool message and persist to storage."""
    for msg in reversed(messages):
        if msg.get("role") != "tool":
            continue
        seq = msg.get("_sequence", 0)
        if seq <= last_retrospect_seq:
            break
        combined = (msg.get("content", "") or "") + f"\n---\nRetrospect: {feedback}"
        msg["content"] = combined
        step_info = step_lookup.get(target_tool_call_id)
        if step_info is not None:
            step_id = step_info.get("id", "")
            if step_id:
                await storage.update_step_condensed_content(
                    session_id, step_id, combined
                )
        break


def _remove_retrospect_tool_call(messages: list[dict[str, Any]]) -> None:
    """Remove the retrospect_tool_result tool call and its result from messages."""
    indices_to_remove: list[int] = []

    retrospect_call_ids: set[str] = set()
    for i, msg in enumerate(messages):
        if msg.get("role") == "assistant" and msg.get("tool_calls"):
            for tc in msg["tool_calls"]:
                fn = tc.get("function", {})
                if fn.get("name") == "retrospect_tool_result":
                    retrospect_call_ids.add(tc.get("id", ""))
                    if len(msg["tool_calls"]) == 1:
                        indices_to_remove.append(i)

    for i, msg in enumerate(messages):
        if (
            msg.get("role") == "tool"
            and msg.get("tool_call_id", "") in retrospect_call_ids
        ):
            indices_to_remove.append(i)

    for i in sorted(indices_to_remove, reverse=True):
        messages.pop(i)


async def maybe_apply_retrospect(
    *,
    feedback: str | None,
    state: "RunContext",
    step_lookup: dict[str, dict[str, Any]],
) -> None:
    """Apply retrospect if a retrospect_tool_result was executed this batch."""
    if feedback is None:
        return
    offload_dir = (
        Path(state.config.get_effective_root_path())
        / ".agiwo"
        / "retrospect"
        / state.session_id
    )
    await execute_retrospect(
        feedback=feedback,
        messages=state.ledger.messages,
        ledger=state.ledger,
        storage=state.session_runtime.run_step_storage,
        session_id=state.session_id,
        offload_dir=offload_dir,
        step_lookup=step_lookup,
    )


__all__ = [
    "check_retrospect_trigger",
    "update_retrospect_tracking",
    "inject_system_notice",
    "execute_retrospect",
    "maybe_apply_retrospect",
    "offload_to_disk",
]
